name: hackyeah
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_popup_card: ^0.0.6
  provider: ^6.0.0

  http: ^0.13.3
  intl: ^0.17.0
  flutter_dotenv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - img/logo_big.png
    - img/logo_small.png
    - .env
  fonts:
    - family: Now
      fonts:
        - asset: fonts/Now-Regular.otf
        - asset: fonts/Now-Medium.otf
          weight: 700
